// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team997.robot.subsystems;

import org.usfirst.frc.team997.robot.RobotMap;
import org.usfirst.frc.team997.robot.commands.*;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Ultrasonic;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class DriveTrain extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private final AnalogGyro driveGyro = RobotMap.driveTrainDriveGyro;
	private final SpeedController leftMotors = RobotMap.driveTrainLeftMotors;
	private final SpeedController rightMotors = RobotMap.driveTrainRightMotors;
	private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
	private final Encoder leftDriveEncoder = RobotMap.driveTrainLeftDriveEncoder;
	private final Encoder rightDriveEncoder = RobotMap.driveTrainRightDriveEncoder;
	private final Ultrasonic ultrasonic = RobotMap.driveTrainUltrasonic;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public void resetEncoders() {
		leftDriveEncoder.reset();
		rightDriveEncoder.reset();
	}

	public void resetGyro() {
		driveGyro.reset();
	}

	public void stop() {
		leftMotors.set(0.0);
		rightMotors.set(0.0);
	}

	public void tankDrive(double left, double right) {
		robotDrive.tankDrive(left, right);
	}

	public void arcadeDrive(double left, double right) {
		robotDrive.arcadeDrive(left, right);
	}

	public double getDistance() {
		return ultrasonic.getRangeInches();
	}

	public double getAngle() {
		return driveGyro.getAngle();
	}

	public int getEncoderCount() {
		return leftDriveEncoder.get();
	}

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	@Override
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		setDefaultCommand(new ManualDrive());

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}
}
